[tool.poetry]
name = "llm-rag-api"
version = "0.1.0"
description = "LLM RAG API"
authors = ["Igor Martinelli <igor.martinelli@usp.br>"]
readme = "README.md"
packages = [{ include = "llm_api" }]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
llama-index-storage-docstore-redis = "^0.1.2"
llama-index-vector-stores-redis = "^0.2.0"
llama-index-embeddings-openai = "^0.1.10"
llama-index-llms-openai = "^0.1.23"
llama-index-storage-chat-store-redis = "^0.1.3"
llama-index-readers-json = "^0.1.5"
llama-index-readers-google = "^0.2.9"
llama-index-readers-file = "^0.1.27"
docx2txt = "^0.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
flake8 = "^7.1.0"
pytest-sugar = "^1.0.0"
pytest-cov = "^5.0.0"
bandit = "^1.7.9"
mypy = "^1.10.0"
pre-commit = "^3.7.1"
black = "^24.4.2"
pytest-asyncio = "^0.23.7"
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
